DEFAULT_GOODBYE_MESSAGES = [
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first} will be missed.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first} just went offline.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first} has left the lobby.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first} has left the clan.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first} has left the game.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first} has fled the area.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first} is out of the running.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nNice knowing ya, {first}!",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nIt was a fun time {first}.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nWe hope to see you again soon, {first}.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nI donut want to say goodbye, {first}.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nGoodbye {first}! Guess who's gonna miss you :')",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nGoodbye {first}! It's gonna be lonely without ya.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nPlease don't leave me alone in this place, {first}!",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nGood luck finding better shit-posters than us, {first}!",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou know we're gonna miss you {first}. Right? Right? Right?",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nCongratulations, {first}! You're officially free of this mess.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\n{first}. You were an opponent worth fighting.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou're leaving, {first}? Yare Yare Daze.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nBring him the photo",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nGo outside!",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nAsk again later",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nThink for yourself",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nQuestion authority",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou are worshiping a sun god",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nDon't leave the house today",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nGive up!",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nMarry and reproduce",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nStay asleep",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nWake up",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nLook to la luna",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nSteven lives",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nMeet strangers without prejudice",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nA hanged man will bring you no luck today",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nWhat do you want to do today?",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou are dark inside",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nHave you seen the exit?",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nGet a baby pet it will cheer you up.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYour princess is in another castle.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou are playing it wrong give me the controller",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nTrust good people",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nLive to die.",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nWhen life gives you lemons reroll!",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nWell, that was worthless",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nI fell asleep!",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nMay your troubles be many",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYour old life lies in ruin",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nAlways look on the bright side",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nIt is dangerous to go alone",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou will never be forgiven",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou have nobody to blame but yourself",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nOnly a sinner",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nUse bombs wisely",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nNobody knows the troubles you have seen",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nYou look fat you should exercise more",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nFollow the zebra",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nWhy so blue?",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nThe devil in disguise",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nGo outside",
    "—✨••÷[  SƈαɾLσɾԃ⚔️  ]÷••✨—\nAlways your head in the clouds",
]
DEFAULT_GOODBYE = "Nice knowing ya!"